version: '3.9'

services:
  php:
    image: zhiqiangwang/php:8.2-fpm-composer
    container_name: php
    volumes:
      - ./tp:/var/www/html
    networks:
      - nginxphp
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./tp:/var/www/html
      - ./tp.config:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - nginxphp

networks:
  nginxphp:
    driver: bridge