ARG IMAGE_TAG="7.4-fpm"

FROM zhiqiangwang/php:${IMAGE_TAG}

RUN apt update 

RUN apt install -y supervisor nginx

ADD ./conf/nginx/default /etc/nginx/sites-enabled/default
ADD ./conf/supervisor/nginx-php.conf /etc/supervisor/conf.d

RUN echo "<?php phpinfo(); ?>" >> /var/www/html/index.php

RUN apt clean && rm -rf /tmp/* && rm -rf /var/log/* && rm -rf /usr/src/php && rm -rf /var/lib/apt/lists/*

EXPOSE 80 9000

CMD ["supervisord", "-u", "root", "-c", "/etc/supervisor/supervisord.conf"]